Level 1/task 7/part 4
PolinaXox/php-course pull request #12
Opened 2024-12-13 11:50 UTC by PolinaXox

2024-12-23 14:45 UTC, anton-moroz requested changes

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/passwords.txt
> +:err
why do you have error login and password pairs here?

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +        checkRequestMethod();
fix identation

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +	if($login === false) {
404 error code not fits here

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +		throw new Exception('Login value is absent(empty field)', 404);
and what is the difference between `if($login === false) {` and  `if(empty($login)) {`?

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +function validateLoginAndPassword(): array {
if your function name contains "And" - this function should be divided to 2 separate functions

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +    return getStringContentAsPairsArray(file_get_contents($filename), $delim1, $delim2);
`file_get_contents` is a bad idea for reading files, especially with ones which will grow with time. do it via file streams

2024-12-23 14:45 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +    return array_filter($pairsAsArr);
what is the sense to go over the array 3 times?

2025-01-14 10:25 UTC, PolinaXox commented on 1. Basics/task_7/part_4/passwords.txt
> +:err
OK. Let`s assume that "password.txt" is perfect (but not sorted)

2025-01-14 10:25 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +        checkRequestMethod();
done

2025-01-14 10:34 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +		throw new Exception('Login value is absent(empty field)', 404);
Conception has been changed. This functional is `checkAuthentication()` for fields existance and `userAuthorization()` for empty/not empty.

2025-01-14 10:35 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +function validateLoginAndPassword(): array {
Conception has been changed. This functional is `userAuthorization()` now.

2025-01-14 10:37 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +    return getStringContentAsPairsArray(file_get_contents($filename), $delim1, $delim2);
Done. Now it reads line by line with `fgets()` in `userAuthorization()`.

2025-01-14 10:39 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +    return array_filter($pairsAsArr);
Conception has been changed.  Now `userAuthorization()` reads the password file line by line and there are no the array at all.

2025-01-14 11:02 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +        checkRequestMethod();
(It was unexpected hard 😢)

2025-01-19 17:06 UTC, anton-moroz requested changes

2025-01-19 17:06 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +		userAuthorization();
method name should sound like an action

2025-01-19 17:06 UTC, anton-moroz commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +		preg_match('#^(.*):(.*)'. PHP_EOL .'$#', fgets($file), $logAndPass);
you can do just `explode()`

2025-01-21 15:08 UTC, PolinaXox commented on 1. Basics/task_7/part_4/task_4_on_apache_handler.php
> +		userAuthorization();
Done, `userAuthorization` -> `authenticateUser()`
(And the other case: `checkAuthentication()` -> `checkRequestBody()`)

2025-01-28 19:22 UTC, anton-moroz approved these changes

2025-01-29 07:22 UTC, merged