level_1/task_7/part_2
PolinaXox/php-course pull request #9
Opened 2024-11-11 12:20 UTC by PolinaXox

2024-11-14 13:02 UTC, anton-moroz requested changes

2024-11-26 15:43 UTC, PolinaXox commented on 1. Basics/task_7/part_2/task_2_on_apache.php
> +$bookId = isset($_REQUEST['bookId']) ? $_REQUEST['bookId'] : '12345';
🆗 Done

2024-11-26 15:44 UTC, PolinaXox commented on 1. Basics/task_7/part_2/task_2_on_apache.php
> +$author = isset($_REQUEST['author']) ? $_REQUEST['author'] : 'Tan Ah Teck';
:ok: Done

2024-11-26 15:48 UTC, PolinaXox commented on 1. Basics/task_7/part_2/task_2_on_apache.php
> +$rbMethodOptionGET = isset($_REQUEST['methodOptions']) && ($_REQUEST['methodOptions'] === 'GET') ? 'checked' : '';
Done. Solution: a new variable stores the value I need.

2024-11-29 14:22 UTC, anton-moroz approved these changes

2024-12-05 09:37 UTC, merged